<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>DeltaEpsilon.Displacement</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>DeltaEpsilon.Displacement</AssemblyName>
        <RunPostBuildEvent>Always</RunPostBuildEvent>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>dev\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Atomcraft">
        <HintPath>dev\Atomcraft.dll</HintPath>
      </Reference>
      <Reference Include="GodotSharp">
        <HintPath>dev\GodotSharp.dll</HintPath>
      </Reference>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="mkdir -p ./DeltaEpsilon.Displacement&#xA;cp ./bin/Release/net8.0/DeltaEpsilon.Displacement.dll ./DeltaEpsilon.Displacement/&#xA;cp ./mod.json ./DeltaEpsilon.Displacement/&#xA;zip -m DeltaEpsilon.Displacement.zip DeltaEpsilon.Displacement/*" />
    </Target>

</Project>
